### ISSUE TITLE
I tried to import Assets, but when I wanted to use it, Unity crashed.

### ISSUE THREAD

**Issue by JZapple2016** [chrisfromwork/AzureKinectUnityWrapper#1]
I use Unity2018.3.10f1 to import it.But when i want to run it in unity scene,the unity is crashed,and   
no prompts or error messages.I dont know how to repair it to use,can you give me some proposal？

**Comment by chrisfromwork** [comment]
This project doesn't have formal support from Microsoft and was created for a hackathon. For any of this logic to work, you will need to build a wrapper dll based on the vcxproj here:
https://github.com/chrisfromwork/Azure-Kinect-Sensor-SDK/blob/develop/examples/AzureKinect.Unity/AzureKinect.Unity.vcxproj

**Comment by chrisfromwork** [comment]
It may be worth giving this another shot. I've added the plugin dlls that you need. Note: this solution is only built for windows pcs

**Comment by chrisfromwork** [comment]
please reopen if you still are having issues.
